# Generated by Django 4.2.17 on 2026-02-07 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=32, unique=True)),
                ('model', models.CharField(max_length=64)),
                ('maintenance_threshold_hours', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_mission', 'In Mission'), ('in_maintenance', 'In Maintenance')], default='available', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_name', models.CharField(max_length=128)),
                ('mission_type', models.CharField(max_length=128)),
                ('mission_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='completed', max_length=16)),
                ('flight_datetime', models.DateTimeField()),
                ('flight_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('fuel_used', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs', to='operations.aircraft')),
                ('arrival_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='operations.base')),
                ('crew_members', models.ManyToManyField(blank=True, related_name='flight_logs', to='operations.crew')),
                ('departure_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='operations.base')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-flight_datetime'],
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='home_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='operations.base'),
        ),
    ]
