# Generated by Django 4.2.17 on 2026-02-07 13:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=64)),
                ('contact_info', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='pilot_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('altitude', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('engine_temp', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fuel_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('heading', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='operations.flightlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='flightlog',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_logs', to='operations.pilot'),
        ),
    ]
